// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1ns/1ps
module neural_network_AXILiteS_s_axi
#(parameter
    C_ADDR_WIDTH = 6,
    C_DATA_WIDTH = 32
)(
    // axi4 lite slave signals
    input  wire                      ACLK,
    input  wire                      ARESETN,
    input  wire                      ACLK_EN,
    input  wire [C_ADDR_WIDTH-1:0]   AWADDR,
    input  wire                      AWVALID,
    output wire                      AWREADY,
    input  wire [C_DATA_WIDTH-1:0]   WDATA,
    input  wire [C_DATA_WIDTH/8-1:0] WSTRB,
    input  wire                      WVALID,
    output wire                      WREADY,
    output wire [1:0]                BRESP,
    output wire                      BVALID,
    input  wire                      BREADY,
    input  wire [C_ADDR_WIDTH-1:0]   ARADDR,
    input  wire                      ARVALID,
    output wire                      ARREADY,
    output wire [C_DATA_WIDTH-1:0]   RDATA,
    output wire [1:0]                RRESP,
    output wire                      RVALID,
    input  wire                      RREADY,
    // user signals
    output wire [31:0]               input_r,
    output wire [31:0]               output_r,
    output wire [31:0]               dense_1_weights,
    output wire [31:0]               dense_1_bias,
    output wire [31:0]               dense_2_weights,
    output wire [31:0]               dense_2_bias
);
//------------------------Address Info-------------------
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of input_r
//        bit 31~0 - input_r[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of output_r
//        bit 31~0 - output_r[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of dense_1_weights
//        bit 31~0 - dense_1_weights[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of dense_1_bias
//        bit 31~0 - dense_1_bias[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of dense_2_weights
//        bit 31~0 - dense_2_weights[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of dense_2_bias
//        bit 31~0 - dense_2_bias[31:0] (Read/Write)
// 0x3c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//------------------------Parameter----------------------
// address bits
localparam
    ADDR_BITS = 6;

// address
localparam
    ADDR_INPUT_R_DATA_0         = 6'h10,
    ADDR_INPUT_R_CTRL           = 6'h14,
    ADDR_OUTPUT_R_DATA_0        = 6'h18,
    ADDR_OUTPUT_R_CTRL          = 6'h1c,
    ADDR_DENSE_1_WEIGHTS_DATA_0 = 6'h20,
    ADDR_DENSE_1_WEIGHTS_CTRL   = 6'h24,
    ADDR_DENSE_1_BIAS_DATA_0    = 6'h28,
    ADDR_DENSE_1_BIAS_CTRL      = 6'h2c,
    ADDR_DENSE_2_WEIGHTS_DATA_0 = 6'h30,
    ADDR_DENSE_2_WEIGHTS_CTRL   = 6'h34,
    ADDR_DENSE_2_BIAS_DATA_0    = 6'h38,
    ADDR_DENSE_2_BIAS_CTRL      = 6'h3c;

// axi write fsm
localparam
    WRIDLE = 2'd0,
    WRDATA = 2'd1,
    WRRESP = 2'd2;

// axi read fsm
localparam
    RDIDLE = 2'd0,
    RDDATA = 2'd1;

//------------------------Local signal-------------------
// axi write
reg  [1:0]           wstate;
reg  [1:0]           wnext;
reg  [ADDR_BITS-1:0] waddr;
wire [31:0]          wmask;
wire                 aw_hs;
wire                 w_hs;
// axi read
reg  [1:0]           rstate;
reg  [1:0]           rnext;
reg  [31:0]          rdata;
wire                 ar_hs;
wire [ADDR_BITS-1:0] raddr;
// internal registers
reg  [31:0]          int_input_r;
reg  [31:0]          int_output_r;
reg  [31:0]          int_dense_1_weights;
reg  [31:0]          int_dense_1_bias;
reg  [31:0]          int_dense_2_weights;
reg  [31:0]          int_dense_2_bias;

//------------------------Body---------------------------
//++++++++++++++++++++++++axi write++++++++++++++++++++++
assign AWREADY = (wstate == WRIDLE);
assign WREADY  = (wstate == WRDATA);
assign BRESP   = 2'b00;  // OKAY
assign BVALID  = (wstate == WRRESP);
assign wmask   = { {8{WSTRB[3]}}, {8{WSTRB[2]}}, {8{WSTRB[1]}}, {8{WSTRB[0]}} };
assign aw_hs   = AWVALID & AWREADY;
assign w_hs    = WVALID & WREADY;

// wstate
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (~ARESETN)
            wstate <= WRIDLE;
        else
            wstate <= wnext;
    end
end

// wnext
always @(*) begin
    case (wstate)
        WRIDLE:
            if (AWVALID)
                wnext = WRDATA;
            else
                wnext = WRIDLE;
        WRDATA:
            if (WVALID)
                wnext = WRRESP;
            else
                wnext = WRDATA;
        WRRESP:
            if (BREADY)
                wnext = WRIDLE;
            else
                wnext = WRRESP;
        default:
            wnext = WRIDLE;
    endcase
end

// waddr
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (aw_hs)
            waddr <= AWADDR[ADDR_BITS-1:0];
    end
end
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++

//++++++++++++++++++++++++axi read+++++++++++++++++++++++
assign ARREADY = (rstate == RDIDLE);
assign RDATA   = rdata;
assign RRESP   = 2'b00;  // OKAY
assign RVALID  = (rstate == RDDATA);
assign ar_hs   = ARVALID & ARREADY;
assign raddr   = ARADDR[ADDR_BITS-1:0];

// rstate
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (~ARESETN)
            rstate <= RDIDLE;
        else
            rstate <= rnext;
    end
end

// rnext
always @(*) begin
    case (rstate)
        RDIDLE:
            if (ARVALID)
                rnext = RDDATA;
            else
                rnext = RDIDLE;
        RDDATA:
            if (RREADY & RVALID)
                rnext = RDIDLE;
            else
                rnext = RDDATA;
        default:
            rnext = RDIDLE;
    endcase
end

// rdata
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (ar_hs) begin
            rdata <= 1'b0;
            case (raddr)
                ADDR_INPUT_R_DATA_0: begin
                    rdata <= int_input_r[31:0];
                end
                ADDR_OUTPUT_R_DATA_0: begin
                    rdata <= int_output_r[31:0];
                end
                ADDR_DENSE_1_WEIGHTS_DATA_0: begin
                    rdata <= int_dense_1_weights[31:0];
                end
                ADDR_DENSE_1_BIAS_DATA_0: begin
                    rdata <= int_dense_1_bias[31:0];
                end
                ADDR_DENSE_2_WEIGHTS_DATA_0: begin
                    rdata <= int_dense_2_weights[31:0];
                end
                ADDR_DENSE_2_BIAS_DATA_0: begin
                    rdata <= int_dense_2_bias[31:0];
                end
            endcase
        end
    end
end
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++

//++++++++++++++++++++++++internal registers+++++++++++++
assign input_r         = int_input_r;
assign output_r        = int_output_r;
assign dense_1_weights = int_dense_1_weights;
assign dense_1_bias    = int_dense_1_bias;
assign dense_2_weights = int_dense_2_weights;
assign dense_2_bias    = int_dense_2_bias;

// int_input_r[31:0]
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_INPUT_R_DATA_0)
            int_input_r[31:0] <= (WDATA[31:0] & wmask) | (int_input_r[31:0] & ~wmask);
    end
end

// int_output_r[31:0]
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_OUTPUT_R_DATA_0)
            int_output_r[31:0] <= (WDATA[31:0] & wmask) | (int_output_r[31:0] & ~wmask);
    end
end

// int_dense_1_weights[31:0]
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_DENSE_1_WEIGHTS_DATA_0)
            int_dense_1_weights[31:0] <= (WDATA[31:0] & wmask) | (int_dense_1_weights[31:0] & ~wmask);
    end
end

// int_dense_1_bias[31:0]
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_DENSE_1_BIAS_DATA_0)
            int_dense_1_bias[31:0] <= (WDATA[31:0] & wmask) | (int_dense_1_bias[31:0] & ~wmask);
    end
end

// int_dense_2_weights[31:0]
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_DENSE_2_WEIGHTS_DATA_0)
            int_dense_2_weights[31:0] <= (WDATA[31:0] & wmask) | (int_dense_2_weights[31:0] & ~wmask);
    end
end

// int_dense_2_bias[31:0]
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_DENSE_2_BIAS_DATA_0)
            int_dense_2_bias[31:0] <= (WDATA[31:0] & wmask) | (int_dense_2_bias[31:0] & ~wmask);
    end
end

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++

endmodule
