// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void neural_network ( float input[784],  float output[10], const float dense_1_weights[784][128], const float dense_1_bias[128], const float dense_2_weights[128][10], const float dense_2_bias[10]);

