// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module neural_network_top (
aresetn,
aclk
);

parameter RESET_ACTIVE_LOW = 1;
input aresetn ;

input aclk ;

wire aresetn;


wire sig_neural_network_ap_rst_n;



neural_network neural_network_U(
    .ap_rst_n(sig_neural_network_ap_rst_n),
    .ap_clk(aclk)
);

neural_network_ap_rst_n_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_n_if_U(
    .dout(sig_neural_network_ap_rst_n),
    .din(aresetn));

endmodule
